### PR TITLE
add russian translation

### PR DESCRIPTION
**Pull request by missytake**
Can a native speaker take a second look at this?

Also I'm not sure if the localization scheme works at all right now, switching chromium to french already doesn't work for me on main branch, I still see the english text. But tests pass, and updating i18next.js doesn't change anything, so maybe it's fine?

### CODE REVIEW

**Review by iequidoo — APPROVED** [review]

**Comment by missytake** [comment]
@iequidoo Now that it's deployed, can you confirm whether the translation is shown for you?

**Comment by iequidoo** [comment]
i.delta.chat still says "Say hello to iequidoo" while https://delta.chat brings me to https://delta.chat/ru/

**Comment by rosano** [comment]
I'm not sure if it was redirecting before, but I thought it would at least check for preferred language. I can access French https://i.delta.chat/?lang=fr and Russian https://i.delta.chat/?lang=ru with a query parameter.

**Comment by iequidoo** [comment]
Yes, i tried to change my preferred language in FF, but that didn't help for http://i.delta.chat. But if i add `?lang=ru`, it works and looks good

**Pull request merged**
