### PR TITLE
Fallbacks, tests, localization, list view

### LINKED ISSUE #10: Fallback functionality
When no invite information is specified, do we imagine:

- leaving it 'broken' (it should only be accessed via the app)
- showing generic information
- showing a form to enter invite details manually (would anyone ever do this as AA becomes more prevalent? and would this be only for individuals or also for groups?)

### PR DESCRIPTION
**Pull request by rosano**
Closes #10 by implementing a form where the QR data can be pasted to generate the invite link. Also styles call-to-action as a numbered list so that people download the app before clicking the open chat button (common fail). Using https://playwright.dev for headless UI tests and https://www.i18next.com for internationalization (just French to start).

### CODE REVIEW

**Comment by rosano** [comment]
Can be tested here https://rosano.github.io/invite/

**Comment by rosano** [comment]
I also set up running the tests via GitHub actions on my fork, can do that here later https://github.com/rosano/invite/actions/workflows/test.yml

**Comment by r10s** [comment]
sorry for being late with review, pretty nice stuff here in this pr 👌

ftr, some screenshots - left: before - middle and right: after

Screenshot 2023-02-25 at 14 26 29 Screenshot 2023-02-25 at 14 26 24 Screenshot 2023-02-25 at 14 26 14

**Review by r10s — APPROVED** [review]
i think, these are great improvements, let's merge it in and iterate from there.

i am a bit unsure about the i18next script, 60k compressed and still quite some boilderplate in the code - i would have expected these things being smarter :) but also here, we can iterate at any point.

for the npm, test stuff and mocha - can you do a README and show a little bit of how this is meant to work? in general, i am pretty happy that it is is still a static html, however.

**Comment by rosano** [comment]
> i am a bit unsure about the i18next script, 60k compressed and still quite some boilderplate in the code - i would have expected these things being smarter :) but also here, we can iterate at any point.

I wasn't aware of the size and can look into smaller versions, as the current needs should be fairly basic. Will make an issue to comment on the boilerplate.

> for the npm, test stuff and mocha - can you do a README and show a little bit of how this is meant to work? in general, i am pretty happy that it is is still a static html, however.

Will do, I tried to avoid build systems.

**Pull request merged**
